 Makefile                |    2 +-
 os/linux/make/macros.mk |    4 ++--
 2 files changed, 3 insertions(+), 3 deletions(-)

--- ixp_osal.orig/Makefile	2005-09-25 05:57:09.000000000 +0200
+++ ixp_osal/Makefile	2005-12-06 21:46:14.000000000 +0100
@@ -185,7 +185,7 @@ endif
 INCLUDE_DIRS = include $(OSAL_DIRS:%=$(MAIN_INC_PREFIX)/%) $(OSAL_DIRS:%=$(OS_INC_PREFIX)/%)  
 
 ifeq ($(IX_OSAL_MK_HOST_OS), linux)
-INCLUDE_DIRS += $(LINUX_SRC)/include/asm-arm/arch-ixp425/
+INCLUDE_DIRS += $(LINUX_SRC)/include/asm-arm/arch-ixp4xx/
 endif
 
 CFLAGS += $(INCLUDE_DIRS:%=-I%) 
--- ixp_osal.orig/os/linux/make/macros.mk	2005-09-25 05:57:02.000000000 +0200
+++ ixp_osal/os/linux/make/macros.mk	2005-12-06 21:46:55.000000000 +0100
@@ -88,10 +88,10 @@ AR := $(LINUX_CROSS_COMPILE)ar
 # Compiler & linker options
 
 # Compiler flags
-LINUX_MACH_CFLAGS := -D__LINUX_ARM_ARCH__=5 -mcpu=xscale -mtune=xscale
+LINUX_MACH_CFLAGS := -D__LINUX_ARM_ARCH__=5 -mtune=xscale
 
 CFLAGS := -D__KERNEL__ -I$(LINUX_SRC)/include -Wall -Wno-trigraphs -fno-common \
-          -pipe -mapcs-32 -mshort-load-bytes -msoft-float -DMODULE \
+          -pipe -mapcs-32 -msoft-float -DMODULE \
           -D__linux -DCPU=33 -DXSCALE=33 $(LINUX_MACH_CFLAGS) -DEXPORT_SYMTAB
 
 # Linux linker flags
