#!/usr/bin/awk -f
BEGIN{
	# The root name - the spurious directory name at the head
	# of the file paths.  Set on the command line to override
	if (base == "")
		base = "linux-2.6.14"
}
$1 == "---" {
	next
}
$1 == "+++" {
	# Rely on the ---/+++ stuff, and +++ (the new one) must have
	# the correct path name!
	path = $2
	sub(/^[^/]+/, base, path)
	print "---", path "	1970-01-01 00:00:00.000000000 +0000"
	print "+++", path "	1970-01-01 00:00:00.000000000 +0000"
	next
}
#Horrible but correct regular expression form:
#( $1 == "---" || $1 == "+++" ) &&
#	$3 ~ /(19[789]|20[0-3])[0-9]-(0[1-9]|1[012])-[0123][0-9]/ &&
#	$4 ~ /[0-9][0-9]:[0-9][0-9]:[0-9][0-9]\.[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]/ &&
#	$5 ~ /[-+][0-9][0-9][0-9][0-9]/{
#	print $1, $2 "	1970-01-01 00:00:00.000000000 +0000"
#	next
#}
{
	print
}
